In [1]:
faqs = """ The lantern flickered in the wind, casting long, wavering shadows across the stone floor. Somewhere beyond the old monastery walls, an owl called out — a sound both haunting and oddly reassuring.

Kieran moved with caution, his fingers tracing the rough outline of a crest etched into the door. Time had worn it down, but the symbol was unmistakable — the twin blades of the Order of Emberlight. He hadn’t seen it since the day the citadel fell.

Dust swirled as the door creaked open, revealing a room cloaked in silence. Shelves lined the walls, filled with brittle scrolls and crumbling tomes. A single desk stood at the center, its surface cluttered with wax seals, broken quills, and parchment.

He approached, heart pounding. Among the pages lay a small, leather-bound book — newer than the rest. The ink was fresh. Someone had been here recently.

As he flipped it open, Kieran found entries written in a careful, looping hand. They spoke of an artifact buried beneath the mountains, one that could awaken the last firekeeper. The legend was real.

Thunder rumbled in the distance as the rain began to fall. He had little time. If the shadows caught his trail, the journey would end before it began.

Far to the east, beyond the dunes and salt-choked air, the city of Arinhal shimmered like a mirage against the setting sun.

Traders from a dozen kingdoms filled the streets, hawking spices, silks, and strange beasts that hissed in gilded cages. Music spilled from open windows, blending with the clatter of hooves and the scent of roasted dates.

Amid the chaos, a young girl with silver eyes moved unnoticed. Her name was Lys. She wore no jewels, no armor — only a threadbare cloak and a quiet determination.

In her palm, she held a coin. One side bore a lion, the other a serpent. She flipped it once, caught it, and smiled. The time had come to choose.

Above her, the moon was rising — pale and full — just as the prophecy had promised."""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer = Tokenizer()

In [6]:
tokenizer.fit_on_texts([faqs])

In [7]:
tokenizer.word_index

{'e': 1,
 'a': 2,
 't': 3,
 'n': 4,
 'o': 5,
 's': 6,
 'i': 7,
 'h': 8,
 'r': 9,
 'd': 10,
 'l': 11,
 'c': 12,
 'the': 13,
 'm': 14,
 'u': 15,
 'g': 16,
 'w': 17,
 'f': 18,
 'b': 19,
 'p': 20,
 'k': 21,
 'y': 22,
 '—': 23,
 'and': 24,
 'v': 25,
 'of': 26,
 'in': 27,
 'it': 28,
 'with': 29,
 'had': 30,
 'was': 31,
 'he': 32,
 'as': 33,
 'j': 34,
 'time': 35,
 'open': 36,
 'to': 37,
 'her': 38,
 'she': 39,
 'q': 40,
 'shadows': 41,
 'beyond': 42,
 'walls': 43,
 'an': 44,
 'kieran': 45,
 'moved': 46,
 'his': 47,
 'door': 48,
 'filled': 49,
 'flipped': 50,
 'one': 51,
 'that': 52,
 'began': 53,
 'caught': 54,
 'from': 55,
 'no': 56,
 '’': 57,
 'x': 58,
 'z': 59,
 'lantern': 60,
 'flickered': 61,
 'wind': 62,
 'casting': 63,
 'long': 64,
 'wavering': 65,
 'across': 66,
 'stone': 67,
 'floor': 68,
 'somewhere': 69,
 'old': 70,
 'monastery': 71,
 'owl': 72,
 'called': 73,
 'out': 74,
 'sound': 75,
 'both': 76,
 'haunting': 77,
 'oddly': 78,
 'reassuring': 79,
 'caution': 80,
 'fingers': 81,
 

In [14]:
input = []
for sentence in faqs.split('.'):
  tokenized_sen =tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sen)):
    n_gram =tokenized_sen[:i+1]
    input.append(n_gram)


In [20]:
max_len = max([len(x) for x in input])

In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input =pad_sequences(input,maxlen = max_len ,  padding = 'pre')

In [25]:
padded_input

array([[  0,   0,   0, ...,   0,  13,  60],
       [  0,   0,   0, ...,  13,  60,  61],
       [  0,   0,   0, ...,  60,  61,  27],
       ...,
       [  0,   0,   0, ...,  33,  13, 248],
       [  0,   0,   0, ...,  13, 248,  30],
       [  0,   0,   0, ..., 248,  30, 249]], dtype=int32)

In [28]:
X= padded_input[:,: -1]

In [29]:
X

array([[  0,   0,   0, ...,   0,   0,  13],
       [  0,   0,   0, ...,   0,  13,  60],
       [  0,   0,   0, ...,  13,  60,  61],
       ...,
       [  0,   0,   0, ..., 247,  33,  13],
       [  0,   0,   0, ...,  33,  13, 248],
       [  0,   0,   0, ...,  13, 248,  30]], dtype=int32)

In [26]:
y = padded_input[: , -1]

In [27]:
y

array([ 60,  61,  27,  13,  62,  63,  64,  65,  41,  66,  13,  67,  68,
        42,  13,  70,  71,  43,  44,  72,  73,  74,  23,   2,  75,  76,
        77,  24,  78,  79,  46,  29,  80,  47,  81,  82,  13,  83,  84,
        26,   2,  85,  86,  87,  13,  48,  30,  88,  28,  89,  90,  13,
        91,  31,  92,  23,  13,  93,  94,  26,  13,  95,  26,  96,  97,
        98,  28,  99,  13, 100,  13, 101, 102, 104,  33,  13,  48, 105,
        36, 106,   2, 107, 108,  27, 109, 111,  13,  43,  49,  29, 112,
       113,  24, 114, 115, 116, 117, 118, 119,  13, 120, 121, 122, 123,
        29, 124, 125, 126, 127,  24, 128, 129, 130, 131,  13, 133, 134,
         2, 135, 136, 137, 138,  23, 139, 140,  13, 141, 142,  31, 143,
        30, 145, 146, 147,  32,  50,  28,  36,  45, 148, 149, 150,  27,
         2, 151, 152, 153, 155,  26,  44, 156, 157, 158,  13, 159,  51,
        52, 160, 161,  13, 162, 163, 164,  31, 165, 167,  27,  13, 168,
        33,  13, 169,  53,  37, 170,  30, 171,  35,  13,  41,  5

In [33]:
from tensorflow.keras.utils import to_categorical
y= to_categorical(y,250)

In [34]:
y.shape

(315, 250)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [51]:
model = Sequential()

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

model = Sequential()
model.add(Embedding(input_dim=250, output_dim=100, input_length=max_len))
model.add(Bidirectional(LSTM(256, return_sequences=True)))   # more units + bidirectional
model.add(Dropout(0.3))
model.add(LSTM(256))                                          # stack another LSTM
model.add(Dropout(0.3))
model.add(Dense(250, activation='softmax'))


In [57]:
model.compile(loss= 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [59]:
model.build(input_shape=( None, max_len))
model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 23, 100)        │        25,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 23, 512)        │       731,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 23, 512)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 256)            │       787,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 250)            │        64,250 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,607,842 (6.13 MB)

 Trainable params: 1,607,842 (6.13 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 23, 100)        │        25,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 23, 512)        │       731,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 23, 512)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 256)            │       787,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 250)            │        64,250 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,607,842 (6.13 MB)

 Trainable params: 1,607,842 (6.13 MB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.fit(X,y,epochs = 100)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 9s 283ms/step - accuracy: 0.0518 - loss: 5.5013
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 289ms/step - accuracy: 0.0836 - loss: 5.2723
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 6s 405ms/step - accuracy: 0.0974 - loss: 5.0849
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 300ms/step - accuracy: 0.0974 - loss: 4.9970
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 292ms/step - accuracy: 0.0856 - loss: 4.9935
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 409ms/step - accuracy: 0.1061 - loss: 4.9134
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 286ms/step - accuracy: 0.1102 - loss: 4.6824
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 295ms/step - accuracy: 0.1031 - loss: 4.6428
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 385ms/step - accuracy: 0.1058 - loss: 4.5240
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 292ms/step - accuracy: 0.0875 - loss: 4.5708
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - accuracy: 0.1192 - loss: 4.3201
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 5

In [63]:
import numpy as np

In [65]:
import time
text = "Kieran moved "

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Kieran moved  with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Kieran moved  with caution
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Kieran moved  with caution his
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Kieran moved  with caution his fingers
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Kieran moved  with caution his fingers tracing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Kieran moved  with caution his fingers tracing the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Kieran moved  with caution his fingers tracing the dunes
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
Kieran moved  with caution his fingers tracing the dunes and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Kieran moved  with caution his fingers tracing the dunes and revealing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Kieran moved  with caution his fingers tracing the dunes and revealing a
